x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
    volumes:
      - prometheus_data:/prometheus
    logging: *default-logging
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik & Authelia
        traefik.enable: "true"
        traefik.http.routers.prometheus.rule: Host(`prometheus.${DOMAIN_NAME}`)
        traefik.http.routers.prometheus.entrypoints: websecure
        traefik.http.routers.prometheus.middlewares: authelia
        traefik.http.services.prometheus.loadbalancer.server.port: 9090
        traefik.http.routers.prometheus.tls: "true"
        # Portainer
        com.docker.compose.project: argus
    networks:
      - internal
      - aether-net
    labels:
      com.docker.compose.project: argus

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN_NAME}
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Authelia
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE=/run/secrets/argus_grafana_oidc_secret
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email groups
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://auth.${DOMAIN_NAME}/api/oidc/authorization
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://auth.${DOMAIN_NAME}/api/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://auth.${DOMAIN_NAME}/api/oidc/userinfo
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'admins') && 'Admin' || 'Viewer'
    secrets:
      - argus_grafana_oidc_secret
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik & Authelia
        traefik.enable: "true"
        traefik.http.routers.grafana.rule: Host(`grafana.${DOMAIN_NAME}`)
        traefik.http.routers.grafana.entrypoints: websecure
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        traefik.http.routers.grafana.tls: "true"
        # Portainer
        com.docker.compose.project: argus
    networks:
      - internal
      - aether-net
    labels:
      com.docker.compose.project: argus

  node-exporter:
    image: prom/node-exporter:latest
    hostname: "{{.Node.Hostname}}"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging: *default-logging
    deploy:
      mode: global
    networks:
      - internal
    labels:
      com.docker.compose.project: argus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    logging: *default-logging
    deploy:
      mode: global
    networks:
      - internal
    labels:
      com.docker.compose.project: argus

volumes:
  prometheus_data:
  grafana_data:


secrets:
  argus_grafana_oidc_secret:
    external: true
    name: ${OIDC_GRAFANA_CLIENT_SECRET_NAME}

networks:
  aether-net:
    external: true
  internal:
    driver: overlay
    attachable: true

configs:
  prometheus_config:
    file: ./configs/prometheus/prometheus.yml
