name: Deploy Argus

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    env:
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      OIDC_GRAFANA_CLIENT_SECRET: ${{ secrets.OIDC_GRAFANA_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Secrets
        run: |
          chmod +x scripts/ensure_secret.sh
          echo "OIDC_GRAFANA_CLIENT_SECRET_NAME=$(echo "$OIDC_GRAFANA_CLIENT_SECRET" | ./scripts/ensure_secret.sh argus_grafana_oidc_secret)" >> $GITHUB_ENV

      - name: Deploy stack
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "argus" docker-compose.yml
